[versions]
micronaut = "4.6.5"
micronaut-docs = "2.0.0"
micronaut-test = "4.5.0"
groovy = "4.0.22"
spock = "2.3-groovy-4.0"

# Managed versions appear in the BOM
managed-guice = "7.0.0"
managed-guava = "33.3.0-jre"

[libraries]
# Core
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }

#
# Managed dependencies appear in the BOM
managed-guice = { module = "com.google.inject:guice", version.ref = "managed-guice" }
managed-guava = { module = "com.google.guava:guava", version.ref = "managed-guava" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params" }
